WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO OFF FEEDBACK ON HEADING ON PAGESIZE 100 LINESIZE 220 VERIFY OFF

PROMPT TDE_STAGE=CONFIGURE
ALTER SYSTEM SET WALLET_ROOT='{{WALLET_ROOT}}' SCOPE=SPFILE;

PROMPT TDE_RESTART_REQUIRED=YES
SHUTDOWN IMMEDIATE;
STARTUP;

ALTER SYSTEM SET TDE_CONFIGURATION='KEYSTORE_CONFIGURATION=FILE' SCOPE=BOTH;
{{OPEN_PDB_COMMANDS}}

ACCEPT wallet_password CHAR PROMPT 'Enter the wallet password locally: ' HIDE
SET TERMOUT OFF
ADMINISTER KEY MANAGEMENT CREATE KEYSTORE IDENTIFIED BY "&wallet_password";
ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY "&wallet_password" {{KEYSTORE_CONTAINER_CLAUSE}};
ADMINISTER KEY MANAGEMENT SET KEY IDENTIFIED BY "&wallet_password" WITH BACKUP {{KEYSTORE_CONTAINER_CLAUSE}};
ADMINISTER KEY MANAGEMENT CREATE AUTO_LOGIN KEYSTORE FROM KEYSTORE IDENTIFIED BY "&wallet_password";
UNDEFINE wallet_password
SET TERMOUT ON

SELECT con_id, status, wallet_type, keystore_mode
FROM v$encryption_wallet
ORDER BY con_id;

SELECT con_id, COUNT(*) AS master_key_count
FROM v$encryption_keys
GROUP BY con_id
ORDER BY con_id;

PROMPT TDE_RESULT=CONFIGURE_COMPLETE
EXIT SUCCESS
