WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET ECHO OFF FEEDBACK ON HEADING ON PAGESIZE 100 LINESIZE 220 VERIFY OFF

PROMPT TDE_STAGE=ENCRYPT_TABLESPACES
PROMPT TDE_TABLESPACE_OFFLINE_REQUIRED=YES

{{TABLESPACE_ENCRYPTION_COMMANDS}}

PROMPT TDE_RESULT=ENCRYPT_TABLESPACES_COMPLETE
EXIT SUCCESS
